

- name: app setup
  include_role:
    name: common
    tasks_from: appsetup.yaml

- name: downnload nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: install application
  include_role: 
    name: common
    tasks_from: serviceusersetup.yaml


- name: copying mongo.repo
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host {{ mongodb_server }} --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  ignore_errors: true
  ignore_unreachable: true

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  ignore_errors: true
  ignore_unreachable: true

- name: load products
  ansible.builtin.shell: mongosh --host {{ mongodb_server }} < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  ignore_errors: true
  ignore_unreachable: true
  
# - name: changing app version
#   tags:
#   - deployment  
#   import_role:
#     name: common
#     tasks_from: deployment.yaml
